name: C++ CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout cod
        uses: actions/checkout@v3

      - name: 2. Instalează dependențele SFML

        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libfreetype-dev libgl1-mesa-dev

      - name: 3. Instalează uneltele (cmake, g++)
        run: sudo apt-get install -y cmake g++

      - name: 4. Configurare CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: 5. Compilare proiect (și SFML)
        run: cmake --build build --config Release

      - name: 6. Verificare executabil
        run: ls -l build/CrossyRoad_Tema